id: A99B50F9B
title: Prayer for the Long Life of Khandro Tsering Chödrön
type: translation
pechas:
- I81A924A7
- I40EA88A4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:30.730558
  last_modified_at: 2023-01-04 12:48:30.730580
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I81A924A7/84C7: B441
  I40EA88A4/4C2F: B441
